/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'Ph:bookOpenTextDuotone': typeof import('~icons/ph/book-open-text-duotone')['default']
    'Ph:notebookDuotone': typeof import('~icons/ph/notebook-duotone')['default']
    'RadixIcons:copy': typeof import('~icons/radix-icons/copy')['default']
    'RadixIcons:moon': typeof import('~icons/radix-icons/moon')['default']
    'RadixIcons:sun': typeof import('~icons/radix-icons/sun')['default']
    'Ri:arrowRightLine': typeof import('~icons/ri/arrow-right-line')['default']
    'Ri:cake2Line': typeof import('~icons/ri/cake2-line')['default']
    'Ri:database2Line': typeof import('~icons/ri/database2-line')['default']
    'Ri:edit2Line': typeof import('~icons/ri/edit2-line')['default']
    'Ri:magicLine': typeof import('~icons/ri/magic-line')['default']
    'Ri:searchLine': typeof import('~icons/ri/search-line')['default']
    'Ri:stackLine': typeof import('~icons/ri/stack-line')['default']
    'Ri:twitterXLine': typeof import('~icons/ri/twitter-x-line')['default']
    'Ri:vipCrownLine': typeof import('~icons/ri/vip-crown-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'SimpleIcons:greensock': typeof import('~icons/simple-icons/greensock')['default']
    'SimpleIcons:nuxtdotjs': typeof import('~icons/simple-icons/nuxtdotjs')['default']
    'SimpleIcons:tailwindcss': typeof import('~icons/simple-icons/tailwindcss')['default']
    'SimpleIcons:vuedotjs': typeof import('~icons/simple-icons/vuedotjs')['default']
  }
}
