/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'Carbon:language': typeof import('~icons/carbon/language')['default']
    'Carbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    'Carbon:logoTwitter': typeof import('~icons/carbon/logo-twitter')['default']
    'Carbon:moon': typeof import('~icons/carbon/moon')['default']
    'Carbon:sun': typeof import('~icons/carbon/sun')['default']
    'Ri:addLine': typeof import('~icons/ri/add-line')['default']
    'Ri:cake2Line': typeof import('~icons/ri/cake2-line')['default']
    'Ri:database2Line': typeof import('~icons/ri/database2-line')['default']
    'Ri:edit2Line': typeof import('~icons/ri/edit2-line')['default']
    'Ri:magicLine': typeof import('~icons/ri/magic-line')['default']
    'Ri:searchLine': typeof import('~icons/ri/search-line')['default']
    'Ri:stackLine': typeof import('~icons/ri/stack-line')['default']
    'Ri:twitterXLine': typeof import('~icons/ri/twitter-x-line')['default']
    'Ri:vipCrownLine': typeof import('~icons/ri/vip-crown-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'SimpleIcons:greensock': typeof import('~icons/simple-icons/greensock')['default']
    'SimpleIcons:nuxtdotjs': typeof import('~icons/simple-icons/nuxtdotjs')['default']
    'SimpleIcons:tailwindcss': typeof import('~icons/simple-icons/tailwindcss')['default']
    'SimpleIcons:vuedotjs': typeof import('~icons/simple-icons/vuedotjs')['default']
  }
}
