/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('~icons/ic/on')['default']
    Iconify: typeof import('~icons/ic/onify')['default']
    'Lucide:arrowUpRight': typeof import('~icons/lucide/arrow-up-right')['default']
    'Lucide:check': typeof import('~icons/lucide/check')['default']
    'Lucide:copy': typeof import('~icons/lucide/copy')['default']
    'Ph:bookOpenTextDuotone': typeof import('~icons/ph/book-open-text-duotone')['default']
    'Ph:notebookDuotone': typeof import('~icons/ph/notebook-duotone')['default']
    'Ph:rocketLaunchDuotone': typeof import('~icons/ph/rocket-launch-duotone')['default']
    'RadixIcons:copy': typeof import('~icons/radix-icons/copy')['default']
    'RadixIcons:moon': typeof import('~icons/radix-icons/moon')['default']
    'RadixIcons:sun': typeof import('~icons/radix-icons/sun')['default']
    'Ri:arrowRightLine': typeof import('~icons/ri/arrow-right-line')['default']
    'Ri:barChart2Line': typeof import('~icons/ri/bar-chart2-line')['default']
    'Ri:cake2Line': typeof import('~icons/ri/cake2-line')['default']
    'Ri:checkLine': typeof import('~icons/ri/check-line')['default']
    'Ri:database2Line': typeof import('~icons/ri/database2-line')['default']
    'Ri:discordLine': typeof import('~icons/ri/discord-line')['default']
    'Ri:edit2Line': typeof import('~icons/ri/edit2-line')['default']
    'Ri:githubFill': typeof import('~icons/ri/github-fill')['default']
    'Ri:githubLine': typeof import('~icons/ri/github-line')['default']
    'Ri:lock2Line': typeof import('~icons/ri/lock2-line')['default']
    'Ri:magicLine': typeof import('~icons/ri/magic-line')['default']
    'Ri:moneyDollarCircleLine': typeof import('~icons/ri/money-dollar-circle-line')['default']
    'Ri:rocket2Line': typeof import('~icons/ri/rocket2-line')['default']
    'Ri:searchLine': typeof import('~icons/ri/search-line')['default']
    'Ri:sparkling2Line': typeof import('~icons/ri/sparkling2-line')['default']
    'Ri:stackLine': typeof import('~icons/ri/stack-line')['default']
    'Ri:twitterXLine': typeof import('~icons/ri/twitter-x-line')['default']
    'Ri:vipCrownLine': typeof import('~icons/ri/vip-crown-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'SimpleIcons:facebook': typeof import('~icons/simple-icons/facebook')['default']
    'SimpleIcons:github': typeof import('~icons/simple-icons/github')['default']
    'SimpleIcons:greensock': typeof import('~icons/simple-icons/greensock')['default']
    'SimpleIcons:instagram': typeof import('~icons/simple-icons/instagram')['default']
    'SimpleIcons:nuxtdotjs': typeof import('~icons/simple-icons/nuxtdotjs')['default']
    'SimpleIcons:producthunt': typeof import('~icons/simple-icons/producthunt')['default']
    'SimpleIcons:tailwindcss': typeof import('~icons/simple-icons/tailwindcss')['default']
    'SimpleIcons:twitter': typeof import('~icons/simple-icons/twitter')['default']
    'SimpleIcons:twitterX': typeof import('~icons/simple-icons/twitter-x')['default']
    'SimpleIcons:vuedotjs': typeof import('~icons/simple-icons/vuedotjs')['default']
    'SimpleIcons:x': typeof import('~icons/simple-icons/x')['default']
  }
}
